### ISSUE TITLE
Steps 1-4 do not work

### ISSUE THREAD

**Issue by Zacoriot** [FlaxEngine/OnlinePlatformSteam#1]
I have been trying to figure out why, when I follow steps 1-4 my project breaks. I cannot open scenes or anything.

here is my log
[Log_2024_06_28_17_53_54.txt](https://github.com/user-attachments/files/16033760/Log_2024_06_28_17_53_54.txt)

**Comment by Zacoriot** [comment]
Pasted version of the Log:
`================================================================
           Start of the log, 2024-06-28 17:53:54
================================================================
[ 00:00:00.004 ]: [Info] Flax Engine
[ 00:00:00.004 ]: [Info] Platform: Windows x64 (Development)
[ 00:00:00.004 ]: [Info] Version 1.8.6512.2
[ 00:00:00.004 ]: [Info] Compiled: May 20 2024 19:12:17 C++14
[ 00:00:00.004 ]: [Info] Compiled with Visual C++ 19.39.33523.00
[ 00:00:00.004 ]: [Info] Product: Flax Editor, Company: Flax
[ 00:00:00.004 ]: [Info] Current culture: en-GB
[ 00:00:00.004 ]: [Info] Command line: -project 'D:\Game Dev\Projects\Flax Projects\Online'
[ 00:00:00.004 ]: [Info] Base folder: D:\Game Dev/Engines/Flax/Flax_1.8
[ 00:00:00.004 ]: [Info] Binaries folder: D:\Game Dev/Engines/Flax/Flax_1.8/Binaries/Editor/Win64/Development/
[ 00:00:00.004 ]: [Info] Temporary folder: C:\Users/isaac/AppData/Local/Temp/d3a3a16d-49c2-b1c2-c35b-35b5ccd48225
[ 00:00:00.004 ]: [Info] Project folder: D:\Game Dev/Projects/Flax Projects/Online
[ 00:00:00.004 ]: [Info] Project name: Online
[ 00:00:00.004 ]: [Info] CPU package count: 1, Core count: 24, Logical processors: 32
[ 00:00:00.004 ]: [Info] CPU Page size: 4 Kb, cache line size: 64 bytes
[ 00:00:00.004 ]: [Info] L1 cache: 2.13 Mb, L2 cache: 32 Mb, L3 cache: 36 Mb
[ 00:00:00.004 ]: [Info] Clock speed: 10 MHz
[ 00:00:00.004 ]: [Info] Physical Memory: 31.84 Gb total, 12.88 Gb used (40.43%)
[ 00:00:00.004 ]: [Info] Virtual Memory: 128 Tb total, 4.32 Gb used (0%)
[ 00:00:00.004 ]: [Info] Main thread id: 0x5dc0, Process id: 1940
[ 00:00:00.004 ]: [Info] Desktop size: X:1920 Y:1080
[ 00:00:00.004 ]: [Info] Virtual Desktop size: X:0 Y:0 Width:1920 Height:1080
[ 00:00:00.004 ]: [Info] Screen DPI: 96
[ 00:00:00.004 ]: [Info] Microsoft Windows 11 Home 64-bit (10.0.22631)
[ 00:00:00.005 ]: [Info] Last project open version: 1.8.6512
[ 00:00:00.005 ]: [Info] Initialize Objects Removal Service...
[ 00:00:00.005 ]: [Info] Initialize Thread Pool...
[ 00:00:00.005 ]: [Info] Spawning 23 Thread Pool workers
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 0' ID=0x5d78 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 1' ID=0x5dec started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 2' ID=0x11b0 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 8' ID=0x5cd8 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 11' ID=0x5de0 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 10' ID=0x5ea0 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 12' ID=0x5e0c started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 4' ID=0x5dd8 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 6' ID=0x5ea8 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 9' ID=0x3c0c started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 17' ID=0x4874 started with priority Normal
[ 00:00:00.006 ]: [Info] Initialize Time...
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 18' ID=0x5f1c started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 14' ID=0x5e10 started with priority Normal
[ 00:00:00.006 ]: [Info] Initialize ContentStorage...
[ 00:00:00.006 ]: [Info] Initialize JobSystem...
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 3' ID=0x369c started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 7' ID=0x1084 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Job System 5' ID=0x8b4 started with priority AboveNormal
[ 00:00:00.006 ]: [Info] Thread 'Job System 7' ID=0x2f14 started with priority AboveNormal
[ 00:00:00.006 ]: [Info] Thread 'Job System 11' ID=0x5958 started with priority AboveNormal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 13' ID=0x21fc started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 19' ID=0x2cec started with priority Normal
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 5' ID=0x5dd4 started with priority Normal
[ 00:00:00.007 ]: [Info] Thread 'Job System 15' ID=0x5714 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 0' ID=0x246c started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 1' ID=0x345c started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 16' ID=0x2b38 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 2' ID=0x1764 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 4' ID=0x5094 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 15' ID=0xf80 started with priority Normal
[ 00:00:00.007 ]: [Info] Thread 'Job System 3' ID=0x2b70 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Initialize Font Manager...
[ 00:00:00.007 ]: [Info] Thread 'Job System 6' ID=0x5404 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 8' ID=0x2418 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 9' ID=0x5598 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 10' ID=0x2d20 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] FreeType initialized, version: 2.10.0
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 20' ID=0x2724 started with priority Normal
[ 00:00:00.007 ]: [Info] Initialize Content...
[ 00:00:00.007 ]: [Info] Thread 'Job System 12' ID=0x5d98 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 31' ID=0x2c30 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 13' ID=0x5d14 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 14' ID=0x694 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 21' ID=0x5a4c started with priority Normal
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 22' ID=0x3dfc started with priority Normal
[ 00:00:00.007 ]: [Info] Thread 'Job System 18' ID=0x29f8 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Loading Asset Cache D:\Game Dev/Projects/Flax Projects/Online/Cache/AssetsCache.dat...
[ 00:00:00.007 ]: [Info] Thread 'Job System 17' ID=0x5e7c started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 19' ID=0x5eb8 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 20' ID=0x3acc started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 21' ID=0x5d5c started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 22' ID=0x4e70 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 23' ID=0x2c90 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 24' ID=0x2354 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 25' ID=0x2c94 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 26' ID=0x583c started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 28' ID=0x5ecc started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 27' ID=0xf04 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 29' ID=0x2aac started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Job System 30' ID=0x5e68 started with priority AboveNormal
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 16' ID=0x5294 started with priority Normal
[ 00:00:00.008 ]: [Info] Asset Cache loaded 165 entries in 1ms (0 rejected)
[ 00:00:00.008 ]: [Info] Initialize Content Loading Manager...
[ 00:00:00.008 ]: [Info] Creating 12 content loading threads...
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 0' ID=0x255c started with priority Normal
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 1' ID=0x190c started with priority Normal
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 2' ID=0x1c24 started with priority Normal
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 3' ID=0x5d10 started with priority Normal
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 6' ID=0x2db0 started with priority Normal
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 7' ID=0x1908 started with priority Normal
[ 00:00:00.008 ]: [Info] Initialize Localization...
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 9' ID=0x3d34 started with priority Normal
[ 00:00:00.008 ]: [Info] Thread 'Load Thread 8' ID=0x10c0 started with priority Normal
[ 00:00:00.009 ]: [Info] Thread 'Load Thread 4' ID=0x2fa0 started with priority Normal
[ 00:00:00.009 ]: [Info] Thread 'Load Thread 5' ID=0x5eac started with priority Normal
[ 00:00:00.009 ]: [Info] Thread 'Load Thread 11' ID=0x3c60 started with priority Normal
[ 00:00:00.009 ]: [Info] Thread 'Load Thread 10' ID=0x5dbc started with priority Normal
[ 00:00:00.025 ]: [Info] Initialize AssetsImportingManager...
[ 00:00:00.025 ]: [Info] Initialize AssetsExportingManager...
[ 00:00:00.025 ]: [Info] Initialize Shader Cache Manager...
[ 00:00:00.025 ]: [Info] Initialize Shaders Compilation Service...
[ 00:00:00.025 ]: [Info] Thread 'File System Watchers' ID=0x2104 started with priority BelowNormal
[ 00:00:00.025 ]: [Info] Initialize Debug Draw...
[ 00:00:00.025 ]: [Info] Initialize GameSettings...
[ 00:00:00.026 ]: [Info] Initialize Input...
[ 00:00:00.026 ]: [Info] Initialize Audio...
[ 00:00:00.026 ]: [Info] Audio system initialization... (backend: OpenAL)
[ 00:00:00.035 ]: [Info] Rebuilding audio contexts
[ 00:00:00.035 ]: [Info] Enabling OpenAL HRTF
[ 00:00:00.059 ]: [Info] OpenAL Soft (1.1 ALSOFT 1.23.1)
[ 00:00:00.059 ]: [Info] [active] Headphones (High Definition Audio Device)
[ 00:00:00.059 ]: [Info] Digital Audio (S/PDIF) (High Definition Audio Device)
[ 00:00:00.059 ]: [Info] Speakers (RODE NT-USB)
[ 00:00:00.059 ]: [Info] VG248 (NVIDIA High Definition Audio)
[ 00:00:00.059 ]: [Info] Initialize Graphics...
================================================================
[ 00:00:00.059 ]: [Info] Creating Graphics Device...
[ 00:00:00.143 ]: [Info] Adapter 0: 'NVIDIA GeForce RTX 4070 SUPER', DirectX 11
[ 00:00:00.143 ]: [Info] 	Dedicated Video Memory: 11.72 Gb, Dedicated System Memory: 0 b, Shared System Memory: 15.92 Gb, Output(s): 1
[ 00:00:00.145 ]: [Info] Adapter 1: 'Microsoft Basic Render Driver', DirectX 11
[ 00:00:00.145 ]: [Info] 	Dedicated Video Memory: 0 b, Dedicated System Memory: 0 b, Shared System Memory: 15.92 Gb, Output(s): 0
[ 00:00:00.201 ]: [Info] Video output '\\.\DISPLAY1' 1920x1080 60 Hz
[ 00:00:00.243 ]: [Info] Total graphics memory: 11.72 Gb
[ 00:00:00.243 ]: [Info] Graphics Device created! Adapter: 'NVIDIA GeForce RTX 4070 SUPER', Renderer: DirectX 11, Shader Profile: DirectX SM5, Feature Level: SM5
================================================================
[ 00:00:00.245 ]: [Info] Initialize Windows Manager...
[ 00:00:00.245 ]: [Info] Initialize Scripting...
[ 00:00:00.245 ]: [Info] Found hostfxr in C:\Program Files\dotnet\host\fxr\8.0.6\hostfxr.dll
[ 00:00:00.283 ]: [Info] .NET runtime version: .NET 8.0.6
[ 00:00:00.285 ]: [Info] Assembly System.Private.CoreLib loaded in 2ms
[ 00:00:00.305 ]: [Info] Caching classes for assembly System.Private.CoreLib took 20ms
[ 00:00:00.307 ]: [Info] Assembly FlaxEngine.CSharp loaded in 1ms
[ 00:00:00.364 ]: [Info] Caching classes for assembly FlaxEngine.CSharp took 57ms
[ 00:00:00.374 ]: [Info] Using FlaxAPI in Development
[ 00:00:00.377 ]: [Info] Main render task created
[ 00:00:00.377 ]: [Info] Scripting Engine initializated! (time: 133ms)
[ 00:00:00.378 ]: [Info] Initialize Animations...
[ 00:00:00.378 ]: [Info] Initialize Editor Analytics...
[ 00:00:00.378 ]: [Info] Editor analytics service is enabled. Curl version: 7.64.1
[ 00:00:00.378 ]: [Info] Initialize Viewport Icons Renderer...
[ 00:00:00.378 ]: [Info] Initialize Scripts Builder...
[ 00:00:00.378 ]: [Info] Initialize Prefab Manager...
[ 00:00:00.378 ]: [Info] Initialize Code Editing Manager...
[ 00:00:00.382 ]: [Info] Initialize Behaviors...
[ 00:00:00.382 ]: [Info] Initialize Physics...
[ 00:00:00.382 ]: [Info] Setup NVIDIA PhysX 5.1.3
[ 00:00:00.383 ]: [Info] Initialize Profiling Tools...
[ 00:00:00.383 ]: [Info] Initialize Custom Editors Util...
[ 00:00:00.407 ]: [Info] Assembly 'FlaxEngine.CSharp' scanned for custom editors in 22 ms
[ 00:00:00.407 ]: [Info] Initialize Game Cooker...
[ 00:00:00.407 ]: [Info] Initialize Render2D...
[ 00:00:00.407 ]: [Info] Initialize Renderer...
[ 00:00:00.409 ]: [Info] Initialize Terrain Manager...
[ 00:00:00.409 ]: [Info] Initialize Atmosphere Pre Compute...
[ 00:00:00.409 ]: [Info] Initialize Navigation...
[ 00:00:00.409 ]: [Info] Initialize Particle Manager...
[ 00:00:00.409 ]: [Info] Initialize ShadowsOfMordor Builder...
[ 00:00:00.409 ]: [Info] Initialize CSG Builder...
[ 00:00:00.409 ]: [Info] Initialize Plugin Manager...
[ 00:00:00.409 ]: [Info] Initialize Streaming...
[ 00:00:00.409 ]: [Info] Initialize Scene Manager...
[ 00:00:00.409 ]: [Info] Initialize Screen...
[ 00:00:00.409 ]: [Info] Initialize Probes Renderer...
[ 00:00:00.409 ]: [Info] Initialize Online...
[ 00:00:00.409 ]: [Info] Initialize Network Manager...
[ 00:00:00.409 ]: [Info] Initialize Network Replication...
[ 00:00:00.409 ]: [Info] Engine services are ready!
[ 00:00:00.409 ]: [Info] Showing splash screen
[ 00:00:00.420 ]: [Info] Setting up C# Editor...
[ 00:00:00.444 ]: [Info] Loaded project Flax, version 1.8.6512.2
[ 00:00:00.453 ]: [Info] Loaded project Online Platform Steam, version 1.0
[ 00:00:00.453 ]: [Info] Loaded project Online, version 1.0
[ 00:00:00.455 ]: [Info] Register Editor module FlaxEditor.Options.OptionsModule
[ 00:00:00.455 ]: [Info] Register Editor module FlaxEditor.Modules.ProjectCacheModule
[ 00:00:00.455 ]: [Info] Register Editor module FlaxEditor.Modules.SceneModule
[ 00:00:00.455 ]: [Info] Register Editor module FlaxEditor.Modules.WindowsModule
[ 00:00:00.457 ]: [Info] Register Editor module FlaxEditor.Modules.UIModule
[ 00:00:00.457 ]: [Info] Register Editor module FlaxEditor.Content.Thumbnails.ThumbnailsModule
[ 00:00:00.457 ]: [Info] Register Editor module FlaxEditor.Modules.SimulationModule
[ 00:00:00.457 ]: [Info] Register Editor module FlaxEditor.Modules.PrefabsModule
[ 00:00:00.457 ]: [Info] Register Editor module FlaxEditor.Modules.SceneEditingModule
[ 00:00:00.457 ]: [Info] Register Editor module FlaxEditor.Modules.ContentEditingModule
[ 00:00:00.458 ]: [Info] Register Editor module FlaxEditor.Modules.ContentDatabaseModule
[ 00:00:00.458 ]: [Info] Register Editor module FlaxEditor.Modules.ContentImportingModule
[ 00:00:00.458 ]: [Info] Register Editor module FlaxEditor.Modules.SourceCodeEditing.CodeEditingModule
[ 00:00:00.458 ]: [Info] Register Editor module FlaxEditor.Modules.SourceCodeEditing.CodeDocsModule
[ 00:00:00.459 ]: [Info] Register Editor module FlaxEditor.Modules.ProgressReportingModule
[ 00:00:00.459 ]: [Info] Register Editor module FlaxEditor.Modules.ContentFindingModule
[ 00:00:00.462 ]: [Info] Changing editor state from  to FlaxEditor.States.LoadingState
[ 00:00:00.463 ]: [Info] Editor init
[ 00:00:00.463 ]: [Info] Options file path: C:\Users\isaac\AppData\Roaming\Flax\EditorOptions.json
[ 00:00:00.463 ]: [Info] Loading editor options
[ 00:00:00.463 ]: [Warning] Missing editor settings
[ 00:00:00.648 ]: [Info] Project database created in 9 ms. Items count: 293
[ 00:00:00.649 ]: [Info] Previews cache count: 1 (capacity for 225 icons)
[ 00:00:00.650 ]: [Info] Add code editor System Default
[ 00:00:00.651 ]: [Info] Add code editor Visual Studio 2022
[ 00:00:00.651 ]: [Info] Add code editor Rider
[ 00:00:00.651 ]: [Info] Add code editor Default
[ 00:00:00.651 ]: [Info] Select code editor Default
================================================================
[ 00:00:00.660 ]: [Info] Starting scripts compilation...
[ 00:00:00.660 ]: [Info] Command: D:\Game Dev/Engines/Flax/Flax_1.8/Binaries/Tools/Flax.Build.exe -log -logfile= -build -mutex -buildtargets=GameEditorTarget -skiptargets=FlaxEditor -platform=Windows -arch=x64 -configuration=Development
[ 00:00:00.797 ]: [Info] Flax.Build 1.0.0
[ 00:00:01.329 ]: [Info] Building targets...
[ 00:00:01.342 ]: [Info] Missing Android SDK. Cannot build for Android platform.
[ 00:00:01.356 ]: [Info] Missing Windows SDK. Cannot build for Windows platform.
[ 00:00:01.358 ]: [Info] Exception: Platform Windows has no required SDK installed and cannot be used.
Stack trace: 
[ 00:00:01.363 ]: [Info]    at Flax.Build.Platform.GetToolchain(TargetArchitecture targetArchitecture) in F:\FlaxEngine\Source\Tools\Flax.Build\Build\Platform.cs:line 266
   at Flax.Build.Builder.BuildTargets() in F:\FlaxEngine\Source\Tools\Flax.Build\Build\Builder.cs:line 362
   at Flax.Build.Program.Main() in F:\FlaxEngine\Source\Tools\Flax.Build\Program.cs:line 152
Total time: 00:00:00.5763323 
[ 00:00:01.369 ]: [Error] Failed to run build tool, result: 1
[ 00:00:01.390 ]: [Info] Editor end init
[ 00:00:01.390 ]: [Info] Changing editor state from FlaxEditor.States.LoadingState to FlaxEditor.States.EditingSceneState
[ 00:00:01.397 ]: [Info] Searching for valid Control
[ 00:00:01.399 ]: [Info] Found 23 types (in 2 ms)
[ 00:00:01.400 ]: [Info] Searching for valid Actor
[ 00:00:01.401 ]: [Info] Found 51 types (in 0 ms)
[ 00:00:01.464 ]: [Info] Loading editor windows layout from 'D:\Game Dev/Projects/Flax Projects/Online/Cache/WindowsLayout.xml'
[ 00:00:01.479 ]: [Info] Closing splash screen
[ 00:00:06.545 ]: [Info] Command: D:\Game Dev/Projects/Flax Projects/Online\Logs 
`

**Comment by mafiesto4** [comment]
`Steamworks` API is in C++ thus it requires C++ Toolchain to be installed for a target platform.

```
Exception: Platform Windows has no required SDK installed and cannot be used.
Stack trace: 
[ 00:00:01.363 ]: [Info]    at Flax.Build.Platform.GetToolchain(TargetArchitecture targetArchitecture) in F:\FlaxEngine\Source\Tools\Flax.Build\Build\Platform.cs:line 266
   at Flax.Build.Builder.BuildTargets() in F:\FlaxEngine\Source\Tools\Flax.Build\Build\Builder.cs:line 362
   at Flax.Build.Program.Main() in F:\FlaxEngine\Source\Tools\Flax.Build\Program.cs:line 152
```

Install Windows SDK and MSVC Toolchain (via Visual Studio). Docs: https://docs.flaxengine.com/manual/scripting/cpp/index.html#setup
